/*
SQLyog Community v13.2.1 (64 bit)
MySQL - 10.4.28-MariaDB : Database - backend-project-flag
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`backend-project-flag` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;

USE `backend-project-flag`;

/*Table structure for table `exercises` */

DROP TABLE IF EXISTS `exercises`;

CREATE TABLE `exercises` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `muscle` varchar(50) NOT NULL,
  `difficulty` enum('beginner','intermediate','expert') NOT NULL,
  `image` varchar(100) DEFAULT NULL,
  `instructions` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=141 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Data for the table `exercises` */

insert  into `exercises`(`id`,`name`,`muscle`,`difficulty`,`image`,`instructions`,`created_at`,`updated_at`) values 
(1,'Barbell curls','biceps','beginner','/gifs/barbell-curls.gif','Stand up straight with your feet shoulder-width apart and hold a barbell with an underhand grip, palms facing forward. Keep your elbows close to your torso and exhale as you curl the weights while contracting your biceps. Continue to raise the bar until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Inhale as you slowly begin to lower the bar back to the starting position.','2024-04-23 16:41:08','2024-05-13 19:34:03'),
(2,'Barbell lying preacher curls','biceps','intermediate','/gifs/barbell-lying-preacher-curl.gif','Sit on a preacher bench with your chest against the pad and your arms extended over the edge, holding a barbell with an underhand grip. Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the bar until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Inhale and slowly begin to lower the barbell back to the starting position.','2024-04-23 16:41:43','2024-05-22 18:11:35'),
(3,'Barbell preacher curls','biceps','intermediate','/gifs/barbell-preacher-curl.gif','Sit on a preacher bench with your upper arms resting on the pad and your chest against the support. Grasp the barbell with an underhand grip, slightly wider than shoulder-width apart. Keeping your upper arms stationary, exhale and curl the barbell up towards your shoulders. Pause for a moment at the top, squeezing your biceps. Inhale and slowly lower the barbell back down to the starting position.\r\n','2024-04-23 16:42:13','2024-05-22 18:11:40'),
(4,'Barbel reverse curls','biceps, forearms','beginner','/gifs/barbell-reverse-curl.gif','Stand up straight with your feet shoulder-width apart and hold a barbell with an overhand grip, palms facing down. Keep your upper arms stationary and exhale as you curl the barbell upward, contracting your biceps. Continue to raise the barbell until your biceps are fully contracted and the barbell is at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Inhale as you slowly lower the barbell back to the starting position, keeping your upper arms stationary.','2024-04-23 16:42:31','2024-05-25 21:23:49'),
(5,'Assisted dip (kneeling)','triceps, shoulders, chest','beginner','/gifs/assisted-dip.gif','Adjust the machine to your desired weight and height. Kneel down on the pad facing the machine, with your hands gripping the handles. Lower your body by bending your elbows, keeping your back straight and close to the machine. Pause for a moment at the bottom, then push yourself back up to the starting position.','2024-04-23 16:43:53','2024-05-25 21:58:42'),
(6,'Barbell close-grip bench press','triceps, chest','intermediate','/gifs/barbell-close-grip-bench-press.gif','Lie flat on a bench with your feet flat on the ground and your back pressed against the bench. Grasp the barbell with a close grip, slightly narrower than shoulder-width apart. Unrack the barbell and lower it slowly towards your chest, keeping your elbows close to your body. Pause for a moment when the barbell touches your chest. Push the barbell back up to the starting position, fully extending your arms.','2024-04-23 16:43:55','2024-05-25 21:42:55'),
(22,'Alternate lateral pulldown','back','beginner','/gifs/alternate-lateral-pulldown.gif','','2024-05-13 15:37:19','2024-05-13 19:34:21'),
(29,'Band alternating biceps curls','biceps','beginner','/gifs/band-alternating-biceps-curls.gif','Stand with your feet shoulder-width apart and hold the band with an underhand grip, palms facing up. Keep your elbows close to your sides and slowly curl one arm up towards your shoulder, squeezing your biceps at the top. Lower the arm back down to the starting position and repeat with the other arm. Continue alternating arms for the desired number of repetitions.','2024-05-25 20:49:37','2024-05-31 15:17:12'),
(30,'Band concentration curl','biceps','intermediate','/gifs/band-concentration-curl.gif','Sit on a bench or chair with your legs spread apart and your feet flat on the ground. Hold one end of the band in your hand and step on the other end with your foot on the same side. Lean forward slightly and rest your elbow on the inside of your thigh, just above the knee. With your palm facing up, slowly curl your hand towards your shoulder, keeping your upper arm stationary. Pause for a moment at the top, then slowly lower your hand back down to the starting position. Repeat for the desired number of repetitions, then switch sides.','2024-05-25 20:59:21','2024-05-31 15:16:05'),
(31,'Band one arm overhead biceps curl','biceps','intermediate','/gifs/band-one-arm-overhead-biceps-curl.gif','Stand with your feet shoulder-width apart and place one end of the band under your foot. Hold the other end of the band with your arm fully extended overhead, palm facing forward. Keeping your upper arm stationary, curl your forearm towards your shoulder, squeezing your biceps. Pause for a moment at the top, then slowly lower your forearm back to the starting position. Repeat for the desired number of repetitions, then switch arms.','2024-05-25 21:05:36','2024-05-31 15:17:03'),
(33,'Barbell alternate biceps curl','biceps, forearms','expert','/gifs/barbell-alternate-biceps-curl.gif','Stand up straight with your feet shoulder-width apart and hold a barbell in each hand, palms facing forward. Keep your upper arms stationary and exhale as you curl the weights while contracting your biceps. Continue to raise the barbells until your biceps are fully contracted and the barbells are at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Inhale as you slowly begin to lower the barbells back to the starting position. Repeat for the desired number of repetitions, alternating arms.','2024-05-25 21:10:23','2024-05-31 15:17:38'),
(34,'Barbell biceps curl (with arm blaster)','biceps','expert','/gifs/barbell-biceps-curl-with-arm-blaster.gif','Stand up straight with your feet shoulder-width apart and hold a barbell with an underhand grip, palms facing up. Place your upper arms against the arm blaster, keeping your elbows close to your torso. Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the barbell until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Inhale and slowly begin to lower the barbell back to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:11:39','2024-05-31 15:16:23'),
(35,'Barbell prone incline curl','biceps, forearms','expert','/gifs/barbell-prone-incline-curl.gif','Set up an incline bench at a 45-degree angle. Lie face down on the bench with your chest and stomach resting against it. Hold a barbell with an underhand grip, shoulder-width apart. Extend your arms fully, allowing the barbell to hang down towards the floor. Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the barbell until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Inhale and slowly begin to lower the barbell back to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:14:32','2024-05-25 21:14:32'),
(36,'Barbell reverse preacher curl','biceps, forearms','expert','/gifs/barbell-reverse-preacher-curl.gif','Sit on a preacher bench with your chest against the pad and your arms extended straight down, holding a barbell with an overhand grip. Keeping your upper arms stationary, exhale and curl the barbell upward while contracting your biceps. Continue to raise the barbell until your biceps are fully contracted and the barbell is at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Inhale and slowly lower the barbell back to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:21:37','2024-05-25 21:21:37'),
(37,'Barbell standing close grip curl','biceps, forearms','beginner','/gifs/barbell-standing-close-grip-curl.gif','Stand up straight with your feet shoulder-width apart and hold a barbell with an underhand grip, hands close together. Keep your elbows close to your torso and your upper arms stationary throughout the movement. Exhale as you curl the weights while contracting your biceps. Continue to raise the bar until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Inhale as you slowly begin to bring the barbell back to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:22:59','2024-05-25 21:22:59'),
(38,'Cable close grip curl','biceps','beginner','/gifs/cable-close-grip-curl.gif','Attach a straight bar to a low pulley cable machine. Stand facing the machine with your feet shoulder-width apart and your knees slightly bent. Grasp the bar with an underhand grip, hands shoulder-width apart. Keep your elbows close to your sides and your upper arms stationary throughout the exercise. Exhale and curl the bar up towards your shoulders, contracting your biceps. Pause for a moment at the top of the movement, squeezing your biceps. Inhale and slowly lower the bar back to the starting position, fully extending your arms. Repeat for the desired number of repetitions.','2024-05-25 21:29:28','2024-05-31 15:15:41'),
(39,'Cable hammer curl (with rope)','biceps, forearms','beginner','/gifs/cable-hammer-curl-with-rope.gif','Stand upright with your feet shoulder-width apart and a slight bend in your knees. Hold the cable rope attachment with an underhand grip, palms facing each other, and your arms fully extended. Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the cable rope attachment until your biceps are fully contracted and the rope is at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Inhale and slowly begin to lower the cable rope attachment back to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:37:13','2024-05-25 21:37:13'),
(40,'Band close-grip push-up','triceps, chest, shoulders','intermediate','/gifs/band-close-grip-push-up.gif','Place a band around your upper arms, just above the elbows. Assume a push-up position with your hands directly under your shoulders and your body in a straight line from head to heels. Bend your elbows and lower your chest towards the ground, keeping your elbows close to your sides. Push through your palms to extend your arms and return to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:40:30','2024-05-25 21:40:30'),
(41,'Band side triceps extension','triceps','intermediate','/gifs/band-side-triceps-extension.gif','Stand with your feet shoulder-width apart and hold the band with both hands, palms facing down. Extend your arms straight out to the sides, keeping them parallel to the ground. Slowly bend your elbows and bring your hands towards your shoulders, keeping your upper arms still. Pause for a moment, then slowly extend your arms back out to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:41:54','2024-05-31 15:18:29'),
(42,'Barbell decline close grip to skull press','triceps','intermediate','/gifs/barbell-decline-close-grip-to-skull-press.gif','Lie on a decline bench with your head lower than your feet and hold a barbell with a close grip. Lower the barbell towards your forehead by bending your elbows, keeping your upper arms stationary. Pause for a moment, then extend your arms to press the barbell back up to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:44:18','2024-05-31 15:18:58'),
(43,'Barbell incline close grip bench press','triceps, chest','intermediate','/gifs/barbell-incline-close-grip-bench-press.gif','Set up an incline bench at a 45-degree angle. Lie down on the bench with your feet flat on the ground. Grasp the barbell with a close grip, slightly narrower than shoulder-width apart. Unrack the barbell and lower it slowly towards your chest, keeping your elbows close to your body. Pause for a moment when the barbell touches your chest. Push the barbell back up to the starting position, fully extending your arms. Repeat for the desired number of repetitions.','2024-05-25 21:46:54','2024-05-31 15:19:21'),
(44,'Barbell lying back of the head tricep extension','triceps','intermediate','/gifs/barbell-lying-back-of-the-head-tricep-extension.gif','Lie flat on a bench with your feet flat on the ground and your head at the end of the bench. Hold a barbell with an overhand grip, hands shoulder-width apart, and extend your arms straight up over your chest. Keeping your upper arms stationary, slowly lower the barbell behind your head by bending your elbows. Pause for a moment, then extend your arms back up to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:48:39','2024-05-31 15:19:44'),
(45,'Barbell lying close-grip triceps extension','triceps, shoulders','expert','/gifs/barbell-lying-close-grip-triceps-extension.gif','Lie flat on a bench with your feet flat on the ground and your head at the end of the bench. Grasp the barbell with a close grip, hands shoulder-width apart, palms facing up. Extend your arms fully, lifting the barbell above your chest. Keeping your upper arms stationary, slowly lower the barbell towards your forehead by bending your elbows. Pause for a moment at the bottom, then extend your arms back to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:50:55','2024-05-25 21:50:55'),
(46,'Barbell lying extension','triceps','intermediate','/gifs/barbell-lying-extension.gif','Lie flat on a bench with your feet flat on the ground and your head at the end of the bench. Hold the barbell with an overhand grip, hands shoulder-width apart, and extend your arms straight up over your chest. Keeping your upper arms stationary, slowly lower the barbell towards your forehead by bending your elbows. Pause for a moment, then extend your arms back up to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:52:05','2024-05-31 15:20:45'),
(47,'Barbell reverse grip skullcrusher','triceps','intermediate','/gifs/barbell-reverse-grip-skullcrusher.gif','Lie flat on a bench with your feet flat on the ground and your head at the end of the bench. Hold the barbell with a reverse grip, palms facing towards your face, and your hands shoulder-width apart. Extend your arms straight up over your chest, keeping your elbows in and your wrists straight. Slowly lower the barbell towards your forehead by bending your elbows, keeping your upper arms stationary. Pause for a moment at the bottom, then extend your arms back up to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:53:57','2024-05-25 21:54:33'),
(48,'Barbell seated close grip behind neck triceps exte','triceps, shoulders','intermediate','/gifs/barbell-seated-close-grip-behind-neck-triceps-extension.gif','Sit on a bench with your back straight and feet flat on the ground. Hold the barbell with a close grip behind your neck, palms facing forward. Keep your elbows close to your head and slowly lower the barbell towards the back of your head. Pause for a moment, then extend your arms back up to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:55:54','2024-05-25 21:55:54'),
(49,'Bench dip (knees bent)','triceps, chest, shoulders','beginner','/gifs/bench-dip-knees-bent.gif','Sit on the edge of a bench or chair with your hands gripping the edge next to your hips. Slide your butt off the bench and straighten your legs in front of you, keeping your heels on the ground. Bend your elbows and lower your body towards the ground, keeping your back close to the bench. Pause for a moment at the bottom, then push yourself back up to the starting position. Repeat for the desired number of repetitions.','2024-05-25 21:57:25','2024-05-25 21:57:25'),
(50,'Bodyweight kneeling triceps extension','triceps, shoulders, chest','beginner','/gifs/bodyweight-kneeling-triceps-extension.gif','Kneel down on the ground with your knees hip-width apart. Place your hands on the ground in front of you, shoulder-width apart, fingers pointing forward. Extend your legs straight behind you, balancing on your toes and hands, forming a straight line from head to heels. Bend your elbows and lower your upper body towards the ground, keeping your elbows close to your sides. Pause for a moment at the bottom, then push through your hands to straighten your arms and return to the starting position. Repeat for the desired number of repetitions.','2024-05-25 22:00:10','2024-05-25 22:00:10'),
(51,'Cable alternate triceps extension','triceps, shoulders','intermediate','/gifs/cable-alternate-triceps-extension.gif','Stand facing the cable machine with your feet shoulder-width apart. Hold the cable handle with your right hand and bring your arm up so that your upper arm is parallel to the ground and your elbow is bent at a 90-degree angle. Keep your upper arm stationary and extend your forearm backward, fully straightening your arm. Pause for a moment, then slowly return to the starting position. Repeat with your left arm. Continue alternating arms for the desired number of repetitions.','2024-05-25 22:01:22','2024-05-25 22:01:22'),
(52,'Cable concentration extension (on knee)','triceps','beginner','/gifs/cable-concentration-extension-on-knee.gif','Sit on a bench or chair with your knees bent and feet flat on the ground. Hold the cable handle with your right hand and place your elbow on the inside of your right knee. Extend your arm fully, keeping your elbow stationary and close to your knee. Pause for a moment at the top, then slowly lower your arm back to the starting position. Repeat for the desired number of repetitions, then switch sides.','2024-05-25 22:02:36','2024-05-25 22:03:31'),
(53,'Cable high pulley overhead tricep extension','triceps, shoulders','intermediate','/gifs/cable-high-pulley-overhead-tricep-extension.gif','Attach a rope to a high pulley and stand facing away from the machine. Grasp the rope with both hands and extend your arms overhead. Keep your elbows close to your head and your upper arms stationary. Slowly lower the rope behind your head by bending your elbows. Pause for a moment, then extend your arms back to the starting position. Repeat for the desired number of repetitions.','2024-05-25 22:04:23','2024-05-25 22:04:23'),
(54,'Cable kickback','triceps','beginner','/gifs/cable-kickback.gif','Stand facing a cable machine with your feet shoulder-width apart. Hold the cable handle with your right hand and step back to create tension in the cable. Bend your knees slightly and hinge forward at the hips, keeping your back straight. Keep your upper arm close to your body and your elbow bent at a 90-degree angle. Extend your forearm backward, straightening your arm fully. Pause for a moment, then slowly return to the starting position. Repeat for the desired number of repetitions, then switch sides.','2024-05-25 22:06:40','2024-05-25 22:06:40'),
(55,'Cable overhead triceps extension (rope attachment)','triceps, shoulders','beginner','/gifs/cable-overhead-triceps-extension-rope-attachment.gif','Attach a rope to a cable machine at a high position. Stand facing away from the machine with your feet shoulder-width apart. Grasp the rope with both hands, palms facing each other, and bring your hands above your head. Keep your upper arms close to your head and your elbows pointing forward. Slowly lower the rope behind your head by bending your elbows. Pause for a moment, then extend your arms back up to the starting position. Repeat for the desired number of repetitions.','2024-05-25 22:08:31','2024-05-25 22:08:31'),
(56,'Cable pushdown','triceps','beginner','/gifs/cable-pushdown.gif','Attach a straight bar to a high pulley cable machine. Stand facing the machine with your feet shoulder-width apart and a slight bend in your knees. Grasp the bar with an overhand grip, hands shoulder-width apart. Keep your elbows close to your sides and your upper arms stationary. Exhale and push the bar down until your elbows are fully extended. Pause for a moment, then inhale and slowly return the bar to the starting position. Repeat for the desired number of repetitions.','2024-05-25 22:10:27','2024-05-27 23:42:23'),
(57,'Cable rear drive','triceps','intermediate','/gifs/cable-rear-drive.gif','Attach a handle to a low pulley cable machine and stand facing away from the machine. Grasp the handle with an overhand grip and extend your arms straight out in front of you. Keeping your elbows stationary, pull the handle back towards your body, squeezing your triceps at the end of the movement. Slowly return the handle to the starting position and repeat for the desired number of repetitions.','2024-05-25 22:12:06','2024-05-31 15:14:16'),
(59,'Band One Arm Twisting Chest Press','chest','intermediate','/gifs/band-one-arm-twisting-chest-press.gif','Attach the band to a sturdy anchor point at chest height. Stand with your side facing the anchor point and grab the band with one hand. Step away from the anchor point to create tension in the band. Position your feet shoulder-width apart and slightly bend your knees. Bring your hand holding the band across your body, towards the opposite shoulder. While maintaining tension in the band, push your hand forward and away from your body, extending your arm. Slowly return to the starting position and repeat for the desired number of repetitions. Switch sides and repeat the exercise with the other hand.','2024-05-31 14:47:44','2024-05-31 15:14:06'),
(60,'Barbell Bench Press','chest','beginner','/gifs/barbell-bench-press.gif','Lie flat on a bench with your feet flat on the ground and your back pressed against the bench. Grasp the barbell with an overhand grip slightly wider than shoulder-width apart. Lift the barbell off the rack and hold it directly above your chest with your arms fully extended. Lower the barbell slowly towards your chest, keeping your elbows tucked in. Pause for a moment when the barbell touches your chest. Push the barbell back up to the starting position by extending your arms. Repeat for the desired number of repetitions.','2024-05-31 14:51:36','2024-05-31 15:14:00'),
(61,'Barbell Decline Bench Press','chest','intermediate','/gifs/barbell-decline-bench-press.gif','Lie on a decline bench with your feet secured and your head lower than your hips. Grasp the barbell with an overhand grip slightly wider than shoulder-width apart. Unrack the barbell and lower it slowly towards your chest, keeping your elbows tucked in. Pause for a moment at the bottom, then push the barbell back up to the starting position. Repeat for the desired number of repetitions.','2024-05-31 14:53:32','2024-05-31 15:13:55'),
(62,'Barbell Front Raise and Pullover','chest, back','expert','/gifs/barbell-front-raise-and-pullover.gif','Stand with your feet shoulder-width apart and hold a barbell with an overhand grip, palms facing down. Keep your arms straight and raise the barbell in front of you until it reaches shoulder height. Pause for a moment at the top, then slowly lower the barbell back down to the starting position. Next, lower the barbell behind your head, keeping your arms straight. Pause for a moment at the bottom, then raise the barbell back up to the starting position. Repeat for the desired number of repetitions.','2024-05-31 14:55:29','2024-05-31 15:13:52'),
(63,'Barbell Incline Bench Press','chest','intermediate','/gifs/barbell-incline-bench-press.gif','Set up an incline bench at a 45-degree angle. Lie down on the bench with your feet flat on the ground. Grasp the barbell with an overhand grip, slightly wider than shoulder-width apart. Unrack the barbell and lower it slowly towards your chest, keeping your elbows at a 45-degree angle. Pause for a moment at the bottom, then push the barbell back up to the starting position. Repeat for the desired number of repetitions.','2024-05-31 14:57:04','2024-05-31 15:13:24'),
(64,'Barbell Reverse Grip Decline Bench Press','chest','expert','/gifs/barbell-reverse-grip-decline-bench-press.gif','Lie on a decline bench with your feet secured and your head lower than your hips. Grasp the barbell with a reverse grip, slightly wider than shoulder-width apart. Unrack the barbell and lower it slowly towards your chest, keeping your elbows tucked in. Pause for a moment at the bottom, then push the barbell back up to the starting position. Repeat for the desired number of repetitions.','2024-05-31 15:01:01','2024-05-31 15:13:18'),
(65,'Barbell Reverse Grip Incline Bench Press','chest','expert','/gifs/barbell-reverse-grip-incline-bench-press.gif','Set up an incline bench at a 45-degree angle. Lie down on the bench with your feet flat on the ground. Grasp the barbell with a reverse grip, hands slightly wider than shoulder-width apart. Unrack the barbell and lower it slowly towards your chest, keeping your elbows tucked in. Pause for a moment when the barbell touches your chest. Push the barbell back up to the starting position, fully extending your arms. Repeat for the desired number of repetitions.','2024-05-31 15:02:27','2024-05-31 15:13:14'),
(66,'Barbell Wide Bench Press','chest','expert','/gifs/barbell-wide-bench-press.gif','Lie flat on a bench with your feet flat on the ground and your back pressed against the bench. Grasp the barbell with a wide grip, slightly wider than shoulder-width apart. Lift the barbell off the rack and hold it directly above your chest with your arms fully extended. Lower the barbell slowly towards your chest, keeping your elbows slightly flared out. Pause for a moment when the barbell touches your chest, then push it back up to the starting position. Repeat for the desired number of repetitions.','2024-05-31 15:04:16','2024-05-31 15:13:10'),
(67,'Cable Bench Press','chest','intermediate','/gifs/cable-bench-press.gif','Adjust the cable machine to chest height and attach the handles. Stand facing away from the machine with your feet shoulder-width apart. Grasp the handles with an overhand grip and step forward to create tension in the cables. Position your feet firmly on the ground and engage your core. Bend your elbows and bring your hands to shoulder level, keeping your elbows at a 90-degree angle. Push the handles forward, extending your arms fully in front of you. Pause for a moment, then slowly reverse the movement, bringing your hands back to shoulder level. Repeat for the desired number of repetitions.','2024-05-31 15:05:31','2024-05-31 15:13:05'),
(68,'Cable Cross-Over Variation','chest','intermediate','/gifs/cable-cross-over-variation.gif','Adjust the cable pulleys to chest height. Stand in the center of the cable machine with one foot in front of the other. Grasp the handles with your palms facing down and your arms extended out to the sides. Take a step forward, keeping your arms slightly bent. With a slight bend in your elbows, bring your hands together in front of your chest. Pause for a moment, then slowly return your arms back to the starting position. Repeat for the desired number of repetitions.','2024-05-31 15:06:36','2024-05-31 15:12:59'),
(69,'Cable Decline Fly','chest','intermediate','/gifs/cable-decline-fly.gif','Adjust the cable machine to a decline position. Stand facing away from the machine with your feet shoulder-width apart. Hold the handles with your palms facing forward and your arms extended straight out in front of you. Keeping a slight bend in your elbows, open your arms out to the sides in a controlled motion. Pause for a moment at the fully extended position, then slowly return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 15:11:05','2024-05-31 15:12:54'),
(70,'Cable Decline One Arm Press','chest','intermediate','/gifs/cable-decline-one-arm-press.gif','Adjust the cable machine to a decline position. Stand facing away from the machine and grab the handle with one hand. Position yourself with your back against the decline bench and your arm extended straight in front of you. Bend your elbow and lower the handle towards your chest while keeping your upper arm stationary. Pause for a moment at the bottom, then push the handle back up to the starting position. Repeat for the desired number of repetitions, then switch arms.','2024-05-31 15:32:03','2024-05-31 15:32:03'),
(71,'Cable Decline Press','chest','intermediate','/gifs/cable-decline-press.gif','Adjust the cable machine to a decline position. Sit on the decline bench facing the cable machine. Grasp the handles with an overhand grip and position them at chest level. Keep your feet flat on the ground and your back firmly against the bench. Exhale and push the handles away from your body, extending your arms fully. Pause for a moment at the end of the movement, squeezing your chest muscles. Inhale and slowly return the handles back to the starting position. Repeat for the desired number of repetitions.','2024-05-31 15:33:40','2024-05-31 15:33:40'),
(72,'Cable Incline Fly','chest','intermediate','/gifs/cable-incline-fly.gif','Adjust the cable machine to a low position and attach the handles. Sit on an incline bench with your back against the pad and feet flat on the floor. Grasp the handles with an overhand grip and extend your arms straight out in front of you. Keeping a slight bend in your elbows, open your arms out to the sides in a controlled motion. Pause for a moment at the fully extended position, then slowly return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 15:34:54','2024-05-31 15:35:18'),
(73,'Band Reverse Wrist Curl','forearms','beginner','/gifs/band-reverse-wrist-curl.gif','Sit on a bench or chair with your feet flat on the ground. Hold the band with an overhand grip, palms facing down, and wrap it around your fingers. Rest your forearms on your thighs, with your wrists hanging off the edge. Slowly curl your wrists upward, squeezing your forearms. Pause for a moment at the top, then slowly lower your wrists back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 15:37:25','2024-05-31 15:37:25'),
(74,'Band Wrist Curl','forearms','beginner','/gifs/band-wrist-curl.gif','Sit on a bench or chair with your feet flat on the ground. Hold the band with both hands, palms facing up, and rest your forearms on your thighs. Slowly curl your wrists upward, squeezing your forearms. Pause for a moment at the top, then slowly lower your wrists back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 15:38:26','2024-05-31 15:38:26'),
(75,'Barbell Palms Down Wrist Curl Over a Bench','forearms','intermediate','/gifs/barbell-palms-down-wrist-curl-over-a-bench.gif','Sit on a bench with your feet flat on the ground and your forearms resting on your thighs, palms facing down. Hold a barbell with an overhand grip, hands shoulder-width apart. Lower the barbell towards the ground by flexing your wrists, keeping your forearms stationary. Pause for a moment at the bottom, then slowly raise the barbell back up by extending your wrists. Repeat for the desired number of repetitions.','2024-05-31 15:39:35','2024-05-31 15:39:35'),
(76,'Barbell Palms Up Wrist Curl Over a Bench','forearms','intermediate','/gifs/barbell-palms-up-wrist-curl-over-a-bench.gif','Sit on a bench with your feet flat on the ground and hold a barbell with an underhand grip, palms facing up. Rest your forearms on the bench, allowing your wrists to hang off the edge. Keeping your forearms stationary, exhale and curl your wrists upwards as far as possible. Hold the contracted position for a brief pause, then inhale and slowly lower the barbell back to the starting position. Repeat for the desired number of repetitions.','2024-05-31 15:41:44','2024-05-31 15:41:44'),
(77,'Cable Reverse Wrist Curl','forearms','intermediate','/gifs/cable-reverse-wrist-curl.gif','Attach a cable to a low pulley and sit on a bench facing the cable machine. Grasp the cable handle with an overhand grip, palms facing down. Rest your forearms on your thighs, with your wrists hanging off the edge. Keeping your forearms stationary, exhale and curl your wrists upward as far as possible. Pause for a moment at the top, then inhale and slowly lower your wrists back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 15:43:39','2024-05-31 15:43:39'),
(78,'Cable Wrist Curl','forearms','intermediate','/gifs/cable-wrist-curl.gif','Attach a straight bar to a low pulley cable machine. Stand facing the machine with your feet shoulder-width apart. Grasp the bar with an underhand grip, palms facing up, and your hands shoulder-width apart. Rest your forearms on a bench or pad, with your wrists hanging off the edge. Keeping your forearms stationary, exhale and curl your wrists upward as far as possible. Pause for a moment at the top, then inhale and slowly lower the bar back to the starting position. Repeat for the desired number of repetitions.','2024-05-31 15:44:47','2024-05-31 15:44:47'),
(79,'Barbell Bench Front Squat','legs','intermediate','/gifs/barbell-bench-front-squat.gif','Start by standing with your feet shoulder-width apart and the barbell resting on your upper chest, just below your collarbone. Hold the barbell with an overhand grip, keeping your elbows up and your upper arms parallel to the ground. Lower your body down into a squat position by bending at the knees and hips, keeping your back straight and your chest up. Pause for a moment at the bottom of the squat, then push through your heels to return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:04:18','2024-05-31 16:04:18'),
(80,'Barbell Bench Squat','legs','intermediate','/gifs/barbell-bench-squat.gif','Set up a barbell on a squat rack at chest height. Stand facing away from the rack, with your feet shoulder-width apart. Bend your knees and lower your body down into a squat position, keeping your back straight and chest up. Grasp the barbell with an overhand grip, slightly wider than shoulder-width apart. Lift the barbell off the rack and step back, ensuring your feet are still shoulder-width apart. Lower your body down into a squat, keeping your knees in line with your toes. Pause for a moment at the bottom, then push through your heels to return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:05:27','2024-05-31 16:05:27'),
(81,'Barbell One Leg Squat','legs','expert','/gifs/barbell-one-leg-squat.gif','Stand with your feet shoulder-width apart and hold a barbell across your upper back. Lift one foot off the ground and extend it forward, keeping it parallel to the ground. Bend your standing leg and lower your body down as if sitting back into a chair, keeping your chest up and your back straight. Lower yourself until your thigh is parallel to the ground, then push through your heel to return to the starting position. Repeat for the desired number of repetitions, then switch legs and repeat.','2024-05-31 16:06:43','2024-05-31 16:06:43'),
(82,'Barbell Overhead Squat','legs','beginner','/gifs/barbell-overhead-squat.gif','Stand with your feet shoulder-width apart and toes slightly turned out. Hold the barbell with a wide grip, positioning it overhead with your arms fully extended. Engage your core and lower your body down into a squat position, keeping your chest up and knees tracking over your toes. Pause for a moment at the bottom, then push through your heels to return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:07:49','2024-05-31 16:07:49'),
(83,'Barbell Split Squat V. 2','legs','beginner','/gifs/barbell-split-squat-v-2.gif','Start by standing with your feet shoulder-width apart, holding a barbell across your upper back. Take a large step forward with your right foot, keeping your torso upright. Lower your body by bending your knees and hips until your right thigh is parallel to the ground. Pause for a moment, then push through your right heel to return to the starting position. Repeat with your left leg forward for the desired number of repetitions.','2024-05-31 16:09:30','2024-05-31 16:09:30'),
(84,'Barbell Squat Jump Step Rear Lunge','legs','intermediate','/gifs/barbell-squat-jump-step-rear-lunge.gif','Start by standing with your feet shoulder-width apart, holding a barbell across your upper back. Lower your body into a squat position by bending your knees and pushing your hips back. Explode upwards, jumping off the ground as high as you can. Land softly on your feet and immediately step back with one leg into a reverse lunge. Lower your body down until your front thigh is parallel to the ground, keeping your back straight. Push through your front heel to return to the starting position. Repeat the jump and lunge sequence on the other leg. Continue alternating legs for the desired number of repetitions.','2024-05-31 16:10:54','2024-05-31 16:10:54'),
(85,'Barbell Wide Squat','legs','beginner','/gifs/barbell-wide-squat.gif','Stand with your feet wider than shoulder-width apart, toes pointing slightly outward. Hold the barbell across your upper back, resting it on your traps or rear delts. Engage your core and keep your chest up as you lower your body down into a squat, pushing your hips back and bending your knees. Lower until your thighs are parallel to the ground, or as low as you can comfortably go. Pause for a moment at the bottom, then push through your heels to return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:11:59','2024-05-31 16:11:59'),
(86,'Dumbbell Goblet Squat','legs','intermediate','/gifs/dumbbell-goblet-squat.gif','Stand with your feet shoulder-width apart, holding a dumbbell vertically against your chest with both hands. Keeping your chest up and core engaged, lower your body down into a squat position by pushing your hips back and bending your knees. Continue lowering until your thighs are parallel to the ground, or as low as you can comfortably go. Pause for a moment at the bottom, then push through your heels to return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:13:08','2024-05-31 16:13:08'),
(87,'Dumbbell Single Leg Split Squat','legs','beginner','/gifs/dumbbell-single-leg-split-squat.gif','Stand with your feet shoulder-width apart, holding a dumbbell in each hand. Take a step forward with one foot and position your feet so that your front foot is flat on the ground and your back foot is elevated on a bench or step. Lower your body by bending your front knee and hip, keeping your back knee slightly bent and your back heel off the ground. Continue lowering until your front thigh is parallel to the ground, then push through your front heel to return to the starting position. Repeat for the desired number of repetitions, then switch legs and repeat.','2024-05-31 16:14:52','2024-05-31 16:14:52'),
(88,'Lever Alternate Leg Press','legs','intermediate','/gifs/lever-alternate-leg-press.gif','Adjust the seat and foot platform of the leverage machine to your desired position. Sit on the machine with your back against the backrest and your feet on the foot platform. Place your hands on the handles or sides of the machine for stability. Push one foot against the foot platform, extending your leg until it is almost fully straight. Pause for a moment, then slowly bend your leg and return to the starting position. Repeat with the other leg. Continue alternating legs for the desired number of repetitions.','2024-05-31 16:16:44','2024-05-31 16:16:44'),
(89,'Lever Leg Extension','legs','beginner','/gifs/lever-leg-extension.gif','Adjust the seat height and backrest of the machine to fit your body. Sit on the machine with your back against the backrest and your feet on the footpad. Grasp the handles or sidebars for stability. Extend your legs forward by straightening your knees, lifting the weight. Pause for a moment at the top, then slowly lower the weight back to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:17:50','2024-05-31 16:17:50'),
(90,'Smith Chair Squat','legs','intermediate','/gifs/smith-chair-squat.gif','Adjust the height of the smith machine bar to a comfortable position. Stand with your feet shoulder-width apart, toes slightly turned out. Place the barbell across your upper back, resting it on your traps. Engage your core and keep your chest up as you slowly lower your body by bending your knees and hips. Continue lowering until your thighs are parallel to the ground, or as low as you can comfortably go. Pause for a moment, then push through your heels to return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:20:22','2024-05-31 16:20:22'),
(91,'Smith Single Leg Split Squat','legs','intermediate','/gifs/smith-single-leg-split-squat.gif','Stand in front of the smith machine with your feet shoulder-width apart. Place one foot behind you on a bench or step, with your toes pointing forward. Hold onto the smith machine bar for stability. Bend your front knee and lower your body down into a lunge position, keeping your back straight. Pause for a moment at the bottom, then push through your front heel to return to the starting position. Repeat for the desired number of repetitions, then switch legs.','2024-05-31 16:21:34','2024-05-31 16:21:34'),
(92,'Split Squats','legs','beginner','/gifs/split-squats.gif','Stand with your feet shoulder-width apart. Take a step forward with one foot and place it about two feet in front of the other foot. Lower your body by bending your knees and hips, keeping your back straight. Continue lowering until your front thigh is parallel to the ground, and your back knee is hovering just above the ground. Pause for a moment, then push through your front heel to return to the starting position. Repeat for the desired number of repetitions, then switch legs and repeat.','2024-05-31 16:22:47','2024-05-31 16:22:47'),
(93,'Squat on Bosu Ball','legs','beginner','/gifs/squat-on-bosu-ball.gif','Place the bosu ball on the ground with the flat side up. Stand with your feet shoulder-width apart and position yourself on top of the bosu ball. Lower your body down by bending your knees and hips, as if sitting back into a chair. Keep your chest up and your weight on your heels. Lower yourself until your thighs are parallel to the ground. Pause for a moment, then push through your heels to return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:24:07','2024-05-31 16:24:07'),
(94,'Barbell Good Morning','legs, back','expert','/gifs/barbell-good-morning.gif','Start by standing with your feet shoulder-width apart and the barbell resting on your upper back. Keeping your back straight and your core engaged, hinge forward at the hips, pushing your buttocks back as if you were trying to touch the wall behind you with your glutes. Lower your torso until it is parallel to the ground, feeling a stretch in your hamstrings. Pause for a moment, then return to the starting position by squeezing your glutes and pushing your hips forward. Repeat for the desired number of repetitions.','2024-05-31 16:26:33','2024-05-31 16:26:33'),
(95,'Barbell Straight Leg Deadlift','legs, back','expert','/gifs/barbell-straight-leg-deadlift.gif','Stand with your feet shoulder-width apart and your toes pointing forward. Hold the barbell with an overhand grip, hands slightly wider than shoulder-width apart. Bend at your hips and lower the barbell towards the ground, keeping your back straight and your knees slightly bent. Lower the barbell until you feel a stretch in your hamstrings. Engage your hamstrings and glutes to lift the barbell back up to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:27:49','2024-05-31 16:27:49'),
(96,'Dumbbell Lying Leg Curl','legs','beginner','/gifs/dumbbell-lying-leg-curl.gif','Lie flat on your back with your legs extended and a dumbbell resting on your lower abdomen. Bend your knees and bring the dumbbell towards your glutes, keeping your feet flat on the ground. Pause for a moment at the top, then slowly lower the dumbbell back to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:28:54','2024-05-31 16:28:54'),
(97,'Glute-Ham Raise','legs, back','intermediate','/gifs/glute-ham-raise.gif','Adjust the glute-ham raise machine to fit your body. Position yourself face down on the machine with your ankles secured. Place your hands on your chest or cross them over your chest. Engage your hamstrings and glutes to lift your upper body up towards the ceiling. Continue lifting until your body is in a straight line from your head to your heels. Pause for a moment at the top, then slowly lower your body back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:30:15','2024-05-31 16:30:15'),
(98,'Lever Kneeling Leg Curl','legs','beginner','/gifs/lever-kneeling-leg-curl.gif','Adjust the machine to fit your body and select the desired weight. Kneel on the machine facing downwards, with your knees resting on the pad and your feet secured under the footpads. Grasp the handles or the sides of the machine for stability. Keeping your upper body stationary, exhale and curl your legs up towards your glutes by flexing your knees. Pause for a moment at the top of the movement, squeezing your hamstrings. Inhale and slowly lower your legs back to the starting position, fully extending your knees. Repeat for the desired number of repetitions.','2024-05-31 16:32:04','2024-05-31 16:32:04'),
(99,'Lever Lying Leg Curl','legs','beginner','/gifs/lever-lying-leg-curl.gif','Adjust the machine to fit your body and select the desired weight. Lie face down on the machine with your legs straight and your heels against the padded lever. Grasp the handles or the sides of the machine for stability. Keeping your upper body stationary, exhale and curl your legs up as far as possible without lifting your hips off the pad. Hold the contracted position for a brief pause as you squeeze your hamstrings. Inhale and slowly lower the lever back to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:33:14','2024-05-31 16:33:14'),
(100,'Lever Seated Leg Curl','legs','beginner','/gifs/lever-seated-leg-curl.gif','Adjust the machine to fit your body and sit on it with your back against the backrest. Place your lower legs under the padded lever, just above your ankles. Grasp the handles on the sides of the machine for support. Keeping your upper legs stationary, exhale and curl your legs up as far as possible. Hold the contracted position for a brief pause as you squeeze your hamstrings. Inhale and slowly lower the lever back to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:35:00','2024-05-31 16:35:00'),
(101,'3/4 Sit-Up','abdominals','beginner','/gifs/3-4-sit-up.gif','Lie flat on your back with your knees bent and feet flat on the ground. Place your hands behind your head with your elbows pointing outwards. Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle. Pause for a moment at the top, then slowly lower your upper body back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:37:42','2024-05-31 16:37:42'),
(102,'45° Side Bend','abdominals','beginner','/gifs/45-side-bend.gif','Stand with your feet shoulder-width apart and your arms extended straight down by your sides. Keeping your back straight and your core engaged, slowly bend your torso to one side, lowering your hand towards your knee. Pause for a moment at the bottom, then slowly return to the starting position. Repeat on the other side. Continue alternating sides for the desired number of repetitions.','2024-05-31 16:38:45','2024-05-31 16:38:45'),
(103,'Air Bike','abdominals','beginner','/gifs/air-bike.gif','Lie flat on your back with your hands placed behind your head. Lift your legs off the ground and bend your knees at a 90-degree angle. Bring your right elbow towards your left knee while simultaneously straightening your right leg. Return to the starting position and repeat the movement on the opposite side, bringing your left elbow towards your right knee while straightening your left leg. Continue alternating sides in a pedaling motion for the desired number of repetitions.','2024-05-31 16:39:38','2024-05-31 16:39:38'),
(104,'Alternate Heel Touchers','abdominals','beginner','/gifs/alternate-heel-touchers.gif','Lie flat on your back with your knees bent and feet flat on the ground. Extend your arms straight out to the sides, parallel to the ground. Engaging your abs, lift your shoulders off the ground and reach your right hand towards your right heel. Return to the starting position and repeat on the left side, reaching your left hand towards your left heel. Continue alternating sides for the desired number of repetitions.','2024-05-31 16:40:35','2024-05-31 16:40:35'),
(105,'Arm Slingers Hanging Bent Knee Legs','abdominals','expert','/gifs/arm-slingers-hanging-bent-knee-legs.gif','Hang from a pull-up bar with your arms fully extended and your knees bent at a 90-degree angle. Engage your core and lift your knees towards your chest, bringing them as close to your elbows as possible. Slowly lower your legs back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:41:38','2024-05-31 16:41:58'),
(106,'Arm Slingers Hanging Straight Legs','abdominals','expert','/gifs/arm-slingers-hanging-straight-legs.gif','Hang from a pull-up bar with your arms fully extended and your legs straight down. Engage your core and lift your legs up in front of you until they are parallel to the ground. Hold for a moment at the top, then slowly lower your legs back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:43:01','2024-05-31 16:43:01'),
(107,'Assisted Lying Leg Raise with Lateral Throw Down','abdominals','intermediate','/gifs/assisted-lying-leg-raise-with-lateral-throw-down.gif','Lie flat on your back with your legs extended and your arms by your sides. Place your hands under your glutes for support. Engage your abs and lift your legs off the ground, keeping them straight. While keeping your legs together, lower them to one side until they are a few inches above the ground. Pause for a moment, then lift your legs back to the starting position. Repeat the movement to the other side. Continue alternating sides for the desired number of repetitions.','2024-05-31 16:44:39','2024-05-31 16:45:33'),
(108,'Assisted Sit-Up','abdominals','beginner','/gifs/assisted-sit-up.gif','Sit on the edge of a bench or have someone hold your feet down. Lie flat on your back with your knees bent and feet flat on the ground. Place your hands behind your head with your elbows pointing outwards. Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle. Pause for a moment at the top, then slowly lower your upper body back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:51:42','2024-05-31 16:51:42'),
(109,'Band Assisted Wheel Rollout','abdominals','intermediate','/gifs/band-assisted-wheel-rollout.gif','Kneel on the floor and hold the handles of the band with both hands, palms facing down. Place the band on the ground in front of you and position your hands shoulder-width apart. Engage your core and slowly roll the wheel forward, extending your body as far as you can while maintaining control. Pause for a moment at the furthest point, then slowly roll the wheel back towards your knees to return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 16:54:20','2024-05-31 16:54:20'),
(110,'Band Kneeling Twisting Crunch','abdominals','intermediate','/gifs/band-kneeling-twisting-crunch.gif','Attach the band to a sturdy anchor point at waist height. Kneel down facing away from the anchor point and hold the band with both hands, keeping your elbows bent and close to your sides. Engage your abs and slowly twist your torso to one side, bringing your hands towards your opposite hip. Pause for a moment, then slowly return to the starting position. Repeat on the other side. Continue alternating sides for the desired number of repetitions.','2024-05-31 16:59:04','2024-05-31 16:59:04'),
(111,'Band Standing Crunch','abdominals','intermediate','/gifs/band-standing-crunch.gif','Attach the band to a sturdy anchor point at waist height. Stand facing away from the anchor point with your feet shoulder-width apart. Hold the band with both hands and bring it up to your chest, keeping your elbows bent and close to your body. Engage your abs and slowly crunch forward, bringing your chest towards your knees. Pause for a moment at the top of the crunch, then slowly return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:00:43','2024-05-31 17:00:43'),
(112,'Barbell Rollout','abdominals','intermediate','/gifs/barbell-rollout.gif','Kneel on the floor and hold a barbell with both hands, shoulder-width apart. Roll the barbell forward, extending your arms and keeping your core engaged. Continue rolling forward until your body is fully extended and your arms are overhead. Pause for a moment, then slowly roll the barbell back towards your knees, maintaining control. Repeat for the desired number of repetitions.','2024-05-31 17:01:51','2024-05-31 17:01:51'),
(113,'Barbell Standing Ab Rollerout','abdominals','expert','/gifs/barbell-standing-ab-rollerout.gif','Stand upright with your feet shoulder-width apart and hold the barbell with both hands in front of your thighs. Engage your core and slowly roll the barbell down towards the ground, keeping your back straight and your arms extended. Continue rolling the barbell forward until your body is fully extended and your hands are directly above your head. Pause for a moment, then slowly roll the barbell back towards your thighs, maintaining control and keeping your core engaged. Repeat for the desired number of repetitions.','2024-05-31 17:03:38','2024-05-31 17:03:56'),
(114,'Bottoms-Up','abdominals','beginner','/gifs/bottoms-up.gif','Lie flat on your back with your legs extended and your arms by your sides. Bend your knees and bring them towards your chest, keeping your feet off the ground. Engaging your abs, lift your hips off the ground, bringing your knees towards your head. Pause for a moment at the top, then slowly lower your hips back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:05:09','2024-05-31 17:05:09'),
(115,'Bridge - Mountain Climber (Cross Body)','abdominals','intermediate','/gifs/bridge-mountain-climber-cross-body.gif','Start in a high plank position with your hands directly under your shoulders and your body in a straight line. Engage your core and lift your right foot off the ground, bringing your right knee towards your left elbow. Return your right foot to the starting position and repeat the movement with your left foot towards your right elbow. Continue alternating sides, moving at a controlled pace. Keep your hips level and avoid lifting your hips too high or sagging them too low. Maintain a steady breathing pattern throughout the exercise. Repeat for the desired number of repetitions.','2024-05-31 17:07:35','2024-05-31 17:07:35'),
(116,'Band Front Lateral Raise','shoulders','beginner','/gifs/band-front-lateral-raise.gif','Stand with your feet shoulder-width apart and hold the band in front of your thighs with your palms facing down. Keep your arms straight and lift the band up in front of you until your arms are parallel to the ground. Pause for a moment at the top, then slowly lower the band back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:11:00','2024-05-31 17:11:00'),
(117,'Band Front Raise','shoulders, triceps','beginner','/gifs/band-front-raise.gif','Stand with your feet shoulder-width apart and hold the band in front of your thighs with your palms facing down. Keep your arms straight and slowly raise them forward until they are parallel to the ground. Pause for a moment at the top, then slowly lower your arms back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:12:59','2024-05-31 17:12:59'),
(118,'Band Reverse Fly','shoulders, back','beginner','/gifs/band-reverse-fly.gif','Attach the band to a stationary object at chest height. Stand with your feet shoulder-width apart and hold the band with both hands in front of you. Keep your arms straight and lift them out to the sides until they are parallel to the ground. Squeeze your shoulder blades together at the top of the movement. Slowly lower your arms back to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:14:15','2024-05-31 17:14:15'),
(119,'Band Standing Rear Delt Row','shoulders','beginner','/gifs/band-standing-rear-delt-row.gif','Stand with your feet shoulder-width apart and place the band under your feet. Hold the band handles with your palms facing each other and your arms extended in front of you. Bend your knees slightly and hinge forward at the hips, keeping your back straight. Pull the band towards your chest, squeezing your shoulder blades together. Pause for a moment at the top, then slowly release the tension and return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:15:35','2024-05-31 17:15:35'),
(120,'Band Y-Raise','shoulders','beginner','/gifs/band-y-raise.gif','Stand with your feet shoulder-width apart and hold the band in front of your thighs with your palms facing inwards. Keep your arms straight and lift them up and out to the sides, forming a \'Y\' shape with your body. Squeeze your shoulder blades together at the top of the movement. Slowly lower your arms back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:17:58','2024-05-31 17:17:58'),
(121,'Barbell Front Raise','shoulders','intermediate','/gifs/barbell-front-raise.gif','Stand with your feet shoulder-width apart and hold a barbell in front of your thighs with an overhand grip. Keep your arms straight and lift the barbell forward and upward until it reaches shoulder level. Pause for a moment at the top, then slowly lower the barbell back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:19:03','2024-05-31 17:19:03'),
(122,'Barbell Rear Delt Row','shoulders','intermediate','/gifs/barbell-rear-delt-row.gif','Stand with your feet shoulder-width apart and knees slightly bent. Hold a barbell with an overhand grip, hands slightly wider than shoulder-width apart. Bend forward at the hips, keeping your back straight and chest up. Pull the barbell towards your chest, squeezing your shoulder blades together. Pause for a moment at the top, then slowly lower the barbell back to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:20:55','2024-05-31 17:20:55'),
(123,'Barbell Seated Overhead Press','shoulders','intermediate','/gifs/barbell-seated-overhead-press.gif','Sit on a bench with your back straight and feet flat on the ground. Hold the barbell with an overhand grip, slightly wider than shoulder-width apart. Lift the barbell off the rack and bring it to shoulder level, with your elbows bent and palms facing forward. Press the barbell overhead by extending your arms fully. Pause for a moment at the top, then slowly lower the barbell back to shoulder level. Repeat for the desired number of repetitions.','2024-05-31 17:22:13','2024-05-31 17:22:13'),
(124,'Barbell Standing Close Grip Military Press','shoulders','intermediate','/gifs/barbell-standing-close-grip-military-press.gif','Stand with your feet shoulder-width apart and hold the barbell with an overhand grip, hands slightly closer than shoulder-width apart. Lift the barbell to shoulder height, keeping your elbows close to your body. Press the barbell overhead, extending your arms fully. Lower the barbell back to shoulder height. Repeat for the desired number of repetitions.','2024-05-31 17:24:00','2024-05-31 17:24:00'),
(125,'Barbell Upright Row','shoulders','intermediate','/gifs/barbell-upright-row.gif','Stand with your feet shoulder-width apart and hold a barbell with an overhand grip, hands slightly wider than shoulder-width apart. Let the barbell hang in front of your thighs, arms fully extended. Keeping your back straight and core engaged, exhale and lift the barbell straight up towards your chin, leading with your elbows. Pause for a moment at the top, then inhale and slowly lower the barbell back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:25:13','2024-05-31 17:25:13'),
(126,'Battling Ropes','shoulders','intermediate','/gifs/battling-ropes.gif','Stand with your feet shoulder-width apart and knees slightly bent. Hold one end of the rope in each hand, with your palms facing each other. Raise your arms to shoulder height, keeping your elbows slightly bent. Begin making alternating waves with the ropes by rapidly raising and lowering each arm. Continue for the desired duration or number of repetitions.','2024-05-31 17:26:36','2024-05-31 17:26:36'),
(127,'Cable Cross-Over Reverse Fly','shoulders','intermediate','/gifs/cable-cross-over-reverse-fly.gif','Attach a D-handle to each low pulley cable and stand in the middle of the cable crossover machine. Grasp the handles with a pronated grip (palms facing down) and take a step forward, positioning your feet shoulder-width apart. Bend your knees slightly and lean forward at the waist, keeping your back straight and your abs engaged. With your arms extended out to the sides and slightly bent at the elbows, exhale and squeeze your shoulder blades together as you pull the cables back and upward in a reverse fly motion. Pause for a moment at the peak contraction, then inhale and slowly return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:27:37','2024-05-31 17:27:37'),
(128,'Cable Kneeling Rear Delt Row (with Rope)','shoulders','intermediate','/gifs/cable-kneeling-rear-delt-row-with-rope.gif','Attach a rope handle to a low cable pulley and kneel down facing the machine. Grasp the rope with a neutral grip (palms facing each other) and extend your arms fully in front of you. Keeping your back straight and core engaged, pull the rope towards your body by retracting your shoulder blades. Squeeze your shoulder blades together at the end of the movement and hold for a brief pause. Slowly release the tension and return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:28:38','2024-05-31 17:28:38'),
(129,'Cable One Arm Lateral Raise','shoulders','intermediate','/gifs/cable-one-arm-lateral-raise.gif','Stand with your feet shoulder-width apart, facing the cable machine. Hold the cable handle with one hand, palm facing down, and stand far enough away from the machine so that there is tension on the cable. Keep your arm straight and slowly raise it out to the side until it is parallel to the ground. Pause for a moment at the top, then slowly lower your arm back down to the starting position. Repeat for the desired number of repetitions, then switch sides.','2024-05-31 17:29:34','2024-05-31 17:29:34'),
(130,'Cable Seated Shoulder Internal Rotation','shoulders','beginner','/gifs/cable-seated-shoulder-internal-rotation.gif','Sit on a bench or chair facing the cable machine with your feet flat on the ground. Hold the cable handle with your arm extended straight out in front of you, parallel to the ground. Keep your elbow slightly bent and your shoulder blades pulled back and down. Slowly rotate your arm inward, bringing the cable handle towards the center of your body. Pause for a moment at the end of the movement, then slowly return to the starting position. Repeat for the desired number of repetitions, then switch arms.','2024-05-31 17:31:36','2024-05-31 17:31:36'),
(131,'Assisted Parallel Close Grip Pull-up','back','beginner','/gifs/assisted-parallel-close-grip-pull-up.gif','Adjust the machine to your desired weight and height. Place your hands on the parallel bars with a close grip, palms facing each other. Hang from the bars with your arms fully extended and your feet off the ground. Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body. Continue pulling until your chin is above the bars. Pause for a moment at the top, then slowly lower your body back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:36:59','2024-05-31 17:37:18'),
(132,'Assisted Pull-Up','back','beginner','/gifs/assisted-pull-up.gif','Adjust the machine to your desired weight and height settings. Grasp the handles with an overhand grip, slightly wider than shoulder-width apart. Hang with your arms fully extended and your feet off the ground. Engage your back muscles and pull your body up towards the handles, keeping your elbows close to your body. Continue pulling until your chin is above the handles. Pause for a moment at the top, then slowly lower your body back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:39:55','2024-05-31 17:50:02'),
(133,'Band Close-Grip Pulldown','back','beginner','/gifs/band-close-grip-pulldown.gif','Attach the band to a high anchor point, such as a pull-up bar or sturdy beam. Stand facing the anchor point and grab the band with an underhand grip, hands shoulder-width apart. Step back to create tension in the band, keeping your feet hip-width apart. Engage your core and keep your back straight as you pull the band down towards your chest, squeezing your shoulder blades together. Pause for a moment at the bottom of the movement, then slowly release the band back to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:41:15','2024-05-31 17:49:55'),
(134,'Band Kneeling One Arm Pulldown','back','intermediate','/gifs/band-kneeling-one-arm-pulldown.gif','Attach the band to a sturdy anchor point above your head. Kneel down and hold the band with one hand, palm facing down. Extend your arm fully overhead, keeping your elbow slightly bent. Engage your lat muscles and pull the band down towards your side, bringing your elbow towards your ribcage. Pause for a moment at the bottom, then slowly release the tension and return to the starting position. Repeat for the desired number of repetitions, then switch sides.','2024-05-31 17:43:01','2024-05-31 17:43:01'),
(135,'Cable Bar Lateral Pulldown','back','intermediate','/gifs/cable-bar-lateral-pulldown.gif','Adjust the cable pulley to a high position and attach a straight bar. Sit facing the cable machine with your feet flat on the ground and your knees slightly bent. Grasp the bar with an overhand grip, slightly wider than shoulder-width apart. Lean back slightly and keep your chest up, maintaining a slight arch in your lower back. Pull the bar down towards your chest, leading with your elbows and squeezing your shoulder blades together. Pause for a moment at the bottom of the movement, then slowly return the bar to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:46:20','2024-05-31 17:49:53'),
(136,'Cable Incline Pushdown','back','intermediate','/gifs/cable-incline-pushdown.gif','Attach a straight bar to a high pulley cable machine. Stand facing away from the machine with your feet shoulder-width apart. Grasp the bar with an overhand grip, hands slightly wider than shoulder-width apart. Lean forward slightly and keep your back straight. Pull the bar down towards your thighs by extending your elbows. Pause for a moment at the bottom, then slowly return the bar to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:47:53','2024-05-31 17:49:47'),
(137,'Cable Lateral Pulldown with V-Bar','back','intermediate','/gifs/cable-lateral-pulldown-with-v-bar.gif','Sit down on the cable pulldown machine and grab the v-bar attachment with an overhand grip. Adjust the knee pad so that your thighs are secured under it. Keep your back straight and lean back slightly. Pull the v-bar down towards your upper chest while keeping your elbows close to your body. Squeeze your back muscles at the bottom of the movement. Slowly return the v-bar to the starting position and repeat for the desired number of repetitions.','2024-05-31 17:49:26','2024-05-31 17:49:26'),
(138,'Close Grip Chin-Up','back','intermediate','/gifs/close-grip-chin-up.gif','Grab the pull-up bar with your palms facing towards you and your hands shoulder-width apart. Hang from the bar with your arms fully extended and your feet off the ground. Engage your back muscles and pull your body up towards the bar, keeping your elbows close to your body. Continue pulling until your chin is above the bar. Pause for a moment at the top, then slowly lower your body back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:52:48','2024-05-31 17:52:48'),
(139,'Lever Pullover','back, shoulders','intermediate','/gifs/lever-pullover.gif','Adjust the seat and handles of the leverage machine to a comfortable position. Sit on the machine with your back against the pad and grasp the handles with an overhand grip. Keep your arms slightly bent and your core engaged. Slowly pull the handles towards your chest, squeezing your lats. Pause for a moment at the peak contraction, then slowly return to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:54:49','2024-05-31 17:54:49'),
(140,'Muscle-Up (on Vertical Bar)','back, biceps, triceps, chest','expert','/gifs/muscle-up.gif','Start by hanging from a vertical bar with your palms facing away from you and your arms fully extended. Engage your core and pull your body up towards the bar, leading with your chest. As you pull yourself up, lean back slightly and bring your elbows towards your sides. Continue pulling until your chest reaches the bar and your elbows are fully bent. Pause for a moment at the top, then slowly lower yourself back down to the starting position. Repeat for the desired number of repetitions.','2024-05-31 17:56:31','2024-05-31 17:57:51');

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Data for the table `users` */

insert  into `users`(`id`,`name`,`password`,`email`,`created_at`,`updated_at`) values 
(1,'Bruno','123456','bruno@email.com','2024-04-24 20:01:07','2024-04-24 20:01:07'),
(2,'Bob','789456','bob@email.com','2024-04-24 20:02:42','2024-04-24 20:02:42'),
(3,'Ana','987654','ana@email.com','2024-04-24 20:03:00','2024-04-24 20:03:00'),
(4,'Mike','$argon2id$v=19$m=65536,t=3,p=4$F1zSy6WMuruokTAWH3RdAg$323U6H7AtYy4eyZvFdzSeRuiUNQ3kDslbdYWISJPkRA','mike@email.com','2024-05-06 17:22:34','2024-05-06 17:22:34'),
(5,'Luis','$argon2id$v=19$m=65536,t=3,p=4$5mPX9IxhAfCEXYeOWeTTFA$V+GC3T+YW9ZgJdM1CK+KeKi26G+5fx/Q1KhSnlqYaO8','luis@email.com','2024-05-06 17:29:21','2024-05-06 17:29:21'),
(6,'Caio','$argon2id$v=19$m=65536,t=3,p=4$JWvEXpiG4lX9phTlShaItA$puMz2d9xEdfOd9RPkVyDhK0V//z1dZ/Kv8NDKYE2q5U','caio@email.com','2024-05-06 19:04:24','2024-05-06 19:04:24'),
(7,'Tania','$argon2id$v=19$m=65536,t=3,p=4$pNcXsFlj05YX6k2gkCjsOw$AXWsh6ra2+vcB4UyL3UMZ6PFKN0XqjJG6DaQN6thGQg','tania@email.com','2024-05-06 21:13:30','2024-05-06 21:13:30'),
(8,'Leo','$argon2id$v=19$m=65536,t=3,p=4$cUQOYMDJzXP1zjuBSrcFjA$qlZmGNRXjPemERzfoLc4o3c+BAP9p81zQ/pqY6w8CC4','leo@email.com','2024-05-06 21:14:45','2024-05-06 21:14:45'),
(9,'Bruno','$argon2id$v=19$m=65536,t=3,p=4$74nBBFTRQTvi4C1IRCweww$Oqycn+3nZ5mn5ESk//JWMdJTdAkselnDwya7AFTAvo4','bruno@gmail.com','2024-05-09 21:17:04','2024-05-09 21:17:04'),
(12,'Felipe','$argon2id$v=19$m=65536,t=3,p=4$Hqho/YKBAH7/YkTFctSchw$am0VgJJzWoqYyFBwPxnA8FcV3R+6CfD4iSsNb/Ut52Q','felipe@gmail.com','2024-05-09 21:25:48','2024-05-09 21:25:48'),
(13,'Carlos','$argon2id$v=19$m=65536,t=3,p=4$Jo2jPOrPzKjOHKkOTts4jw$4bh8Quw0lRZjAWiyMqxfP/XSSWQFwzsKRHyDeXkc+fc','carlos@gmail.com','2024-05-09 21:26:15','2024-05-09 21:26:15'),
(28,'Bruno','$argon2id$v=19$m=65536,t=3,p=4$6LpSk6Y0a8No3Oxerle2HQ$8T0SYqa1bQlAkZygWpPvSis6RmogbmiD62Nqfph3SVU','bruno_777@gmail.com','2024-05-09 21:55:55','2024-05-09 21:55:55'),
(29,'Julia','$argon2id$v=19$m=65536,t=3,p=4$eF8JqU73h31NJ1CCUFT5eg$gdeRDpXf0kqoMnYaEjcNOYvwdMsTqTpYqad1pOa3cJM','julia@gmail.com','2024-05-09 22:30:07','2024-05-09 22:30:07'),
(30,'Bia','$argon2id$v=19$m=65536,t=3,p=4$RPU9b2dq3hpJL/6aA8ozfw$TjUDzi3lYNRmRFKlScbfSsoYDNlMdEPWD63QtwaDMRs','bia@gmail.com','2024-05-09 22:31:02','2024-05-09 22:31:02'),
(31,'Carol','$argon2id$v=19$m=65536,t=3,p=4$O3hfZnPD+P2EZA5o/Clcyw$XISq1sSmUoY1ErLKgQx/TCMw7C1Msz6yA4/YiKglLyg','carol@gmail.com','2024-05-09 22:56:15','2024-05-09 22:56:15'),
(32,'Bruno','$argon2id$v=19$m=65536,t=3,p=4$Iktob1VX7Zj3x2lnHwXEdA$61MsBp+dc+KmZHX6JvqGWzRQpWYIj14cEq23Od5s98Y','bruno@hotmail.com','2024-05-10 18:46:38','2024-05-10 18:46:38'),
(41,'Bruna','$argon2id$v=19$m=65536,t=3,p=4$XnCcOC7RprO7mklRQlD6Ig$aBZO+XoVp5nk+xzGQsQzH3+VJ0fbEF1IysIjXTJ1SYg','bananas','2024-05-15 18:44:55','2024-05-15 18:44:55');

/*Table structure for table `workouts` */

DROP TABLE IF EXISTS `workouts`;

CREATE TABLE `workouts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `workouts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Data for the table `workouts` */

insert  into `workouts`(`id`,`title`,`user_id`) values 
(1,'Segunda(biceps e triceps)',1),
(2,'Treino de força',2),
(23,'lalalala',41),
(24,'lalalala',41),
(25,'lalalala',41),
(26,'qlqr coisa',41),
(27,'lalala',41),
(28,'qwert',41),
(29,'798456',41),
(32,'Costas e Biceps',9),
(44,'Morning routine',9);

/*Table structure for table `workouts_exercises` */

DROP TABLE IF EXISTS `workouts_exercises`;

CREATE TABLE `workouts_exercises` (
  `workout_id` int(11) NOT NULL,
  `exercise_id` int(11) DEFAULT NULL,
  KEY `exercise_id` (`exercise_id`),
  KEY `workout_id` (`workout_id`),
  CONSTRAINT `workouts_exercises_ibfk_1` FOREIGN KEY (`workout_id`) REFERENCES `workouts` (`id`),
  CONSTRAINT `workouts_exercises_ibfk_2` FOREIGN KEY (`exercise_id`) REFERENCES `exercises` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Data for the table `workouts_exercises` */

insert  into `workouts_exercises`(`workout_id`,`exercise_id`) values 
(1,1),
(1,2),
(2,4),
(32,31),
(32,2),
(44,2),
(44,3),
(44,1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
